### ISSUE TITLE
Y-axis scaling

### ISSUE THREAD

**Issue by jschlyter** [Ixam97/CarStatsViewer#109]
Currently, consumption above 90 and below -30 kWh/100km is clipped - is this intentional? Would it make sense to be able to dynamically scale the Y-axis to better visualize this?

**Comment by Ixam97** [comment]
The Y-axis has been dynamic in the past. This was changed because singular peaks in consumption would scale the whole diagramm and normal consumption differences would be less visible. The current range is selected to represent most normal driving situations for a longer Trip.

Values outside that range are not really neccessary I thing. They are just "very high" 😜

**Comment by jschlyter** [comment]
Makes sense.
