### ISSUE TITLE
Bug: no trip start date/time in trip summary

### ISSUE THREAD

**Issue by DoubleYouEl** [Ixam97/CarStatsViewer#132]
I see other users’ screen shots showing the trip start date/time in the trip summary page, but in my tests, I never saw a date - see the attached screenshot. I only use the Dev version for tests, I’m not sure if that is a regression bug or not

![D391EA4E-4789-44BF-8E01-9DAB54259AC6](https://user-images.githubusercontent.com/11661560/221035740-d381524c-347b-4f35-8f4b-55aef731cf9d.jpeg)

**Comment by Ixam97** [comment]
How old is your trip data? I have not seen missing strings in this context yet. If it still is an issui in 0.23 we'll have a closer look at it.

**Comment by DoubleYouEl** [comment]
I will check and send you my data files tomorrow

**Comment by Ixam97** [comment]
I now know why this happens: Lokalise creates empty strings for keys that have not been translated yet. If I push the changes from Lokalise to GitHub and build the App, those missing translations appear empty rather than in English. This will not be an issue with complete translations I think. This is also the cause for your other issue. 

I will have a look at the export settings to not include empty strings in the future.
