### ISSUE TITLE
Feature: Performance stats view

### ISSUE THREAD

**Issue by MicPra** [Ixam97/CarStatsViewer#18]
The measurement is activated with a button and triggered by a speed > 0km/h.  Then ticks are counted up to a speed >= 100km/h and the acceleration from 0 to 100km/h is displayed in seconds

**Comment by marky5525** [comment]
Not sure, if I would like this feature in THIS app. Nice to have, but I think, the priority should be on stats during a trip and not for the performance-test. My 2 cents. 
Enso

**Comment by MicPra** [comment]
In total I agree with that - BUT I like to use as less Apps as possible... and from the subject I guess we can discuss if a acceleration measurement is also a statistic value *smile*

**Comment by Ixam97** [comment]
I actually had the same idea a few days ago. Maybe I'm going to implement a separate Performance-View with some more data of this kind, like a power, acceleration and speed plot that also meassures the time and shows max values for these stats 🤔

**Comment by MicPra** [comment]
great idea! 😃

**Comment by FreshDave29** [comment]
first draft in #42

**Comment by Ixam97** [comment]
@FreshDave29 Actually no. This is planed to be more like the Polestar Performance app to meassure acceleration and such. What you mean is the trip summary 😉

**Comment by Turder84** [comment]
This would be useful for non-Performance pack cars as they would get more info of this type.

**Comment by jkkataja** [comment]
It would most likely require massive amount of work, but it would be excellent to get a "track mode" option also. Adding this comment here as I believe it makes more sense discussing it here instead of creating a new feature request at this stage.

I think inspiration could be taken from both Tesla's track mode (https://www.tesla.com/ownersmanual/model3/en_us/GUID-92CA3DCA-EDA3-4243-861E-2C770F5506FD.html) and also various track/race applications for Android (this just as an one example, https://play.google.com/store/apps/details?id=com.racechrono.app&hl=en&gl=US ).

Ideally, I think the following items would be great:

- temperatures of various components (inverter, battery, etc. - not exposed by the car so cannot be done?)
- G-forces during the session
- ability to retrieve track layout for automatic timers (unknown if these are open source and could be utilized from the example Android app?)
- top speed, best acceleration during session

Obviously, car settings cannot be controlled and that is not my suggestion. And like I mentioned, I do recognize that this is a massive task and might be considered to be something that is out of scope for CSV.

**Comment by Ixam97** [comment]
> It would most likely require massive amount of work, but it would be excellent to get a "track mode" option also.

I have decided to abandon the concept of the performance view for now. CSV is already quite feature rich and developed more towards long time stats tracking. I want to focus on this and not bloat it with extensive features like this. Also, since Im currently wortking with Polestar on publishing CSV I want it to have a clear line and not be a direct competitor to the Performance App from Polestar, possibly hindering publication.

Once CSV reaches a state I call "done" I might tinker with  another app specifically for this kind of data.

**Comment by jkkataja** [comment]
Makes total sense. Awesome if you have time with a new application project in the future.
