### ISSUE TITLE
Help Request: Documentation on how to set up a test track

### ISSUE THREAD

**Issue by Fredyy90** [Ixam97/CarStatsViewer#185]
It would be great is there was some documentation on how to set up a test track for the app.

**Comment by mbrammer** [comment]
@Fredyy90 Did you try to do a setup on your own?

**Comment by mbrammer** [comment]
I tried it today. I already had an Google Play Console account from around 10 years ago.  
But I failed with renaming the  com.ixam97.carStatsViewer to my own package name, to be able to upload the bundle. Android Studio did just nothing when refactoring it.  

So I wasted a few hours of my time and now I don't feel like dealing with it anymore.
If one of the developers would like to help me a little bit, I would be willing to continue and also show the author of the issue what I have done. We would give about 200 people the opportunity to use the app.  
Maybe @Ixam97 ?

**Comment by mbrammer** [comment]
Okay, I finally did it and it's running successfully on my car now 🎉   

I try to write down what I did. Hopfully I didn't miss anything important, since it was manly try and error.  

1. Download/Clone the repo.
2. Rename all occurences of `com.ixam97.carStatsViewer` with your custom package name e.g. `com.YOUR_NAME.carStatsViewer`. Also rename the path `automotive/com/ixam97/` with `automotive/com/YOUR_NAME/`. PS: I wasn't able to refactor the package name with Android Studio. So I did it with vsCode by search/replace.
3. Install [Android Studio](https://developer.android.com/studio).
4. Run Android Studio and go through the Setup Wizard.
5. Open the downloaded Car Stats Viewer folder/repo.
6. Go to "Build" -> "Generate signed Bundle / APK...".
7. Select "Android App Bundle" and hit "Next".
8. Create new "Key store path" (create a `keystorefile.jks` anywhere on your machine), just add some random matching passwords and random certificate data. If all done, go ahead.
9. In the next view, select `devRelease` in "Build variants" and click on "Create".
10. After the bundle was created, you will see a little notification with a link to locate the `.aab` bundle file on your machine.
11. Go to [Google Play Console](https://play.google.com/console/) and create a new App. (On YouTube you will find guides how to setup an app).
12. You have to upload screenshots etc. just use some dummy images in the format they demand.
13. Create an internal test (you will find help for that on YouTube as well).
14. Upload the bundle to the release.
15. Go to "Tester" and create a E-Mail list. Here you can add the Google mail adresses of users that are allowed to test the app.
16. Releasing the app might take some time. At the end of the internal test page, you will find a "Copy link". This is the URL to the test app. You can send this to the testers and use it for yourself.

I think that was it. It took me about 6 hours to figure all this out 😮‍💨 

The following YouTube videos helped me:
https://www.youtube.com/watch?v=5GHT4QtotE4
https://www.youtube.com/watch?v=k9QR3BC1hH4
https://www.youtube.com/watch?v=K1XDMau5-YE

**Comment by Ixam97** [comment]
@mbrammer Thank you first of all for going through all of this and making the list. 
Since I did all of this "learning by doing" I am not confident enough to write a complete guide on this. Also I do not want to encourage people with no coding experience whatsoever to get involved with this since I cannot support them for every little detail regarding publishing.

> Rename all occurences of com.ixam97.carStatsViewer with your custom package name e.g. com.YOUR_NAME.carStatsViewer. Also rename the path automotive/com/ixam97/ with automotive/com/YOUR_NAME/. PS: I wasn't able to refactor the package name with Android Studio. So I did it with vsCode by search/replace.

But please do not do this! I know it works, but it is way too easy to make errors while refactoring. Just rename `applicationId` in the module level `build.gradle`. No refactoring of packages needed!

> In the next view, select devRelease in "Build variants" and click on "Create".

Also, please only publish build variants of `stableRelease`. Dev contains stuff supposed for debugging and testing and this might break the app without my private credentials.

Speaking of credentials: The ABRP-API requires an API-Key. Since I don't want it to be spread publicly it is not contained within the repository (and should not be uploaded to GitHub by any track maintainer!). Contact me privatly on how to integrate it to the app.

> You have to upload screenshots etc. just use some dummy images in the format they demand.

This can be skipped as long as it is only an internal test.

> Create an internal test (you will find help for that on YouTube as well).
Before this you should create a form factor for "automotive" and only upload the bundle to this to prevent the App from being installed on other devices than cars. The Play Console should throw an error whent trying to upload the bundle without this form factor.

**Comment by mbrammer** [comment]
Thanks for your addition :pray:

> Also I do not want to encourage people with no coding experience whatsoever to get involved with this since I cannot support them for every little detail regarding publishing.

At least I am a developer, but didn't work with Android etc. since a decade 😆   
Also I think **only people without a dev/IT background should try this**. Others might fail with this very fast or might not even think about to try this on their own. ⚠️ **So no support for people without programming knowledge** ⚠️ 
So this little guide may at least help some people.  
  
Btw, I have a bunch of open test-seats to offer 😉 

> > Rename all occurences of com.ixam97.carStatsViewer with your custom package name e.g. com.YOUR_NAME.carStatsViewer. Also rename the path automotive/com/ixam97/ with automotive/com/YOUR_NAME/. PS: I wasn't able to refactor the package name with Android Studio. So I did it with vsCode by search/replace.
> 
> But please do not do this! I know it works, but it is way too easy to make errors while refactoring. Also, updating will be more complicated. Just rename `applicationId` in the module level `build.gradle`. No refactoring of packages needed! At least it works fine for other tracks. It's a bit "hack", but that could be said about all of this Track-Stuff 🙃

Alright. I tried this, but the dev console blamed about the package name being used already. Maybe it's a new check within the console to validate the bundle?

> > In the next view, select devRelease in "Build variants" and click on "Create".
> 
> Also, please only publish build variants of `stableRelease`. Dev contains stuff supposed for debugging and testing and this might break the app without my private credentials.

Ah okay. Good to know. Will change that on my bundle 👌 

> > You have to upload screenshots etc. just use some dummy images in the format they demand.
> 
> This can be skipped as long as it is only an internal test.

I assumed this as well, but the console forced me to upload them 🙏  Either a new rule as well or I messed up somewhere before 🤷‍♂️   
  
  
I will create a new bundle later today and try again with just the change of `applicationId` in the `build.gradle`. Will let you guys know if this worked.  
Also I will create the `stableRelease` 😉

**Comment by Ixam97** [comment]
@mbrammer Just to be sure I just created a test app in the Play Console.

> Alright. I tried this, but the dev console blamed about the package name being used already. Maybe it's a new check within the console to validate the bundle?

> I assumed this as well, but the console forced me to upload them

I was able to create the new app and internal test by uploading a bundle just with changed app-ID and no screenshots without a problem. And I didn't have had any problems with this method in the past when creating different bundles for the stable and dev branch for my own testing.

> Also I think only people without a dev/IT background should try this.

Something got mixed up there 😉 I'm not saying people without coding experience can't do that (afaik some of the maintainers are not programmers). But I cannot encourage it, since I can't give any support if someone messes up their fork or something. And hopefully all these internal tests will be obsolete once I figured something out with Polestar. So I can't "oficially" encourage the creation new tracks at all, but it is still welcome when someone goes through this hustle in the meantime 😛

Also please consider sharing the info in the german forums, since we are keeping track of all the different tracks over there and I use it to communicate with the maintainers if something relevant for building bundles changes: https://polestar.fans/t/carstatsviewer-informationen/15027

**Comment by mbrammer** [comment]
I also just created a new app and you're right. I think the issue was that I didn't had "Automotive OS" selected on my first try, when creating a release. Now I created a new app and it worked like you described. I also created a screen record. I will update my post above to have a clear guide here 🤗

**Comment by ivanfmartinez** [comment]
@Ixam97 @mbrammer using this procedures I was able to build and publish, now some users with Volvos in Brazil have started testing the app.

Thanks

**Comment by motoridersd** [comment]
Thank you for this! I had spent some time trying to figure things out on my own, but your guide above is perfect. The video is also very helpful.

**Comment by Ixam97** [comment]
I have now written a short summary of the necessary steps: [Docs](https://github.com/Ixam97/CarStatsViewer/blob/master/docs/BUILD.md)
