### ISSUE TITLE
Odometer in HTTP API

### ISSUE THREAD

**Issue by jschlyter** [Ixam97/CarStatsViewer#193]
Would it be possible to add the current odometer value to the HTTP API? Together with `batteryLevel` this could be used to keep track of long term consumption.

**Comment by Ixam97** [comment]
Sadly not. The odometer property ist protected with system privileges.

**Comment by jschlyter** [comment]
If some apps, e.g., Polestar Journey Log can read it, it ought to be connected to some sort of entitlement that can be discussed with the car manufacturer?

**Comment by jschlyter** [comment]
@Ixam97 we could post timestamp of manual trip reset, distance travelled during trip and energy consumed during trip. If one gather all these I believe one can calculate consumption without the odometer.

**Comment by Ixam97** [comment]
The internal database already has all the data needed to calculate long time stats. It's just a matter of creating a sum. The Odometer is not needed for that (and also would be less percice since it's only a value in km). Consumption values from before the start of the database recording data obviously would not be available.

I'll look into it at some point.
