### ISSUE TITLE
Change: Optimise layout for lower resolution screens

### ISSUE THREAD

**Issue by BeauGiles** [Ixam97/CarStatsViewer#93]
Hi,
Love the app - works absolutely great on my Polestar 2!

My friend has installed it in their Volvo XC40 Recharge, which also runs Android Automotive OS.

The app itself appears to work just fine, but some areas of the screen are cut off.

Please see photo of the XC40 screen;

![IMG_2495](https://user-images.githubusercontent.com/211889/217132031-46a511e3-87cf-41f8-9e64-5b7b40fea2b7.jpeg)

Presumably this is due to the lower resolution (and smaller physical size) of the Volvo XC40 screen (and likely other AAOS based Volvo Cars).

> yes, the xc40 emulator is intended to match with that of the car (which is 768x1024), compared to Polestar 2 (which is 1152x1536) https://groups.google.com/a/android.com/g/automotive-developers/c/YdT6mr9QfRM?pli=1

For future app updates, can changes to the layout be considered to optimise the app for smaller screens / lower resolution screens?
Whether the text size used across the app is made smaller, or the graph at the bottom could be made smaller and lowered on the screen.

**Comment by Ixam97** [comment]
That is a known issue. Every once in a while i also test the app on the Volvo emulator. For now the focus is on the Polestar 2 though because I can test the app under real life conditions on that. 

Once the App is somewhat closer to completion I will have a closer look on styling it for other screen dimensions.

For now I recommend to switch the Wh/km-option on in the settings. The text string for the unit is much shorter and the text does not flow out on the bottom.

**Comment by jschlyter** [comment]
@Ixam97, the entire string for consumption could shorter if we drop the "Inst."/"Momentan" part of it. After all, "Power" is also "Momentan" so IMHO the consumption is as well (and it is constantly changing, so it is pretty obvious that it is).

**Comment by Ixam97** [comment]
I have started to move text sizes and some other UI scalings to dimens.xml. This can be defined for multiple different display sizes allowing adjustments for lower resolution screens. It will take some time to convert everything, but I will use that from now on to make the app better fit Volvo screens.

**Comment by Ixam97** [comment]
I have made most of the strings and icons scale depending on the screen size and density. This is how it will look on a Volvo:

![image](https://user-images.githubusercontent.com/12702685/220668722-0ecb6bf6-6426-433d-93e3-80661c1a140a.png)

The Plot still needs a little work, but no more cut texts.

**Comment by Mausy5043** [comment]
> Once the App is somewhat closer to completion I will have a closer look on styling it for other screen dimensions.

May I suggest that you do this as early on in the project as possible? Changing your visualisations from a fixed screensize to a scaled screensize in order to support whatever a car has installed will be a nightmare. Especially, when manufacturers incorporate to landscape displays or even displays that can be rotated...

Assuming, of course, that the popularity of this app will grow and at some point in the future you'll want to expand to other car brands and models. Volvo (X)C40 is in the picture now, I understand. Volvo EX90 and EX30 owners will want to use it too (I know I will). And I'm sure other EV brands are just over the horizon.

**Comment by Ixam97** [comment]
> May I suggest that you do this as early on in the project as possible?

I have put the most important scaling values into seperate resource files. Depending on the screensize differtent values are used. With the exception of some elements in the plots the app scales fine between Polestar and Volvo. 

I once had a tester using the app on a Renaut Megane e-Tech, but Renault does some weird stuff with the VHAL and the app was far from usable and only showed useless values.

I hope there will be emulators for future Volvo and Poelstar models. Otherwise it will be hard to get the respective dimesions right. 

Regarding other brands, only the Honda emulator ist currently freely available. This will require some changes in the layout since it is a very slim landscape display. I will consider this once I do the planned restructuring of the main views with constraint layouts, making them much more flexible.

**Comment by Ixam97** [comment]
Continued by #213
